name: "UI deploy MainNet"
on:
  release:
    types: [released]

jobs:
  deploy-mainnet:
    name: Deploy to MainNet site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: yarn
    - name: Build site
      run: |
        VUE_APP_INFURA_KEY=${{ secrets.VUE_APP_INFURA_KEY_MAINNET }} VUE_APP_IS_MAINNET=true yarn build
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MAINNET_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.MAINNET_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.MAINNET_AWS_REGION }}
    - name: Deploy site to S3
      run: |
        aws s3 sync --delete --only-show-errors dist/ ${{ secrets.MAINNET_S3_BUCKET }}
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.MAINNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
